AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CloudFormation custom resource to import SSH public keys

Globals:
  Function:
    Timeout: 5

Resources:
  KeyImportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: source/
      Handler: source
      Runtime: go1.x
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - ec2:ImportKeyPair
                - ec2:DeleteKeyPair
              Resource: '*'

Outputs:
  KeyImportFunction:
    Description: "Lambda ARN"
    Value: !GetAtt KeyImportFunction.Arn
    Export:
      Name: SshKeyImportFunc
