name: CloudFormation linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint CloudFormation templates
        uses: scottbrenner/cfn-lint-action@master
        with:
          args: "--include-checks I --ignore-checks I3042 -t **/*.yml"